### ISSUE TITLE
Peer Dependancy Issues when Using Template

### ISSUE THREAD

**Issue by moseswynn** [DomoApps/cra-template#1]
When attempting to use this template, npm tries installing ryuu@4.2.0 and fails because the latest version of ryuu is 4.1.4.

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/60747659/144891587-02ef41fa-ce7d-4802-ad7b-1106400844d5.png">

**Comment by jasonleehodges** [comment]
Thanks for reporting this @moseswynn. This should be resolved at this point since the latest `ryuu` has been released on npm. If you are still experiencing issues, please let me know.
